# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"kir": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://kirankamatmgm.github.io/dlpractice/"

git_url = "https://github.com/kirankamatmgm/dlpractice/tree/master/"

def custom_doc_links(name): return None
